#!/usr/bin/env bash
set -euo pipefail
PASS=0; FAIL=0

assert_eq() {
  if [ "$1" = "$2" ]; then PASS=$((PASS+1)); else echo "FAIL: expected '$2', got '$1' — $3"; FAIL=$((FAIL+1)); fi
}
assert_file_exists() {
  if [ -f "$1" ]; then PASS=$((PASS+1)); else echo "FAIL: $1 missing — $2"; FAIL=$((FAIL+1)); fi
}
assert_file_contains() {
  if grep -q "$2" "$1" 2>/dev/null; then PASS=$((PASS+1)); else echo "FAIL: $1 missing '$2' — $3"; FAIL=$((FAIL+1)); fi
}
assert_contains() {
  if echo "$1" | grep -q "$2" 2>/dev/null; then PASS=$((PASS+1)); else echo "FAIL: output missing '$2' — $3"; FAIL=$((FAIL+1)); fi
}

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CT_SCRIPT="${REPO_ROOT}/scripts/context-tree.sh"

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

CT_DIR="${TMPDIR}/.xgh/context-tree"
mkdir -p "$CT_DIR"
cat > "${CT_DIR}/_manifest.json" <<'EOF'
{"version":1,"team":"test","created":"2026-03-13T00:00:00Z","domains":[]}
EOF

export XGH_CONTEXT_TREE_DIR="$CT_DIR"

# --- Test: sync curate — creates file + updates manifest + generates index ---
bash "$CT_SCRIPT" sync --action curate \
  --domain "authentication" \
  --topic "jwt" \
  --title "JWT Best Practices" \
  --tags "auth,jwt,security" \
  --keywords "jwt,best-practices" \
  --source "auto-curate" \
  --from-agent "claude-code" \
  --body "## Raw Concept
Always validate JWT signature before trusting claims.

## Facts
- category: convention
  fact: Validate JWT signature server-side, never trust client-decoded tokens"

EXPECTED="${CT_DIR}/authentication/jwt/jwt-best-practices.md"
assert_file_exists "$EXPECTED" "curate created knowledge file"
assert_file_contains "$EXPECTED" "importance: 10" "initial importance from curate"

MANIFEST=$(cat "${CT_DIR}/_manifest.json")
assert_contains "$MANIFEST" "jwt-best-practices" "manifest updated by curate"
assert_contains "$MANIFEST" "authentication" "manifest has domain"

assert_file_exists "${CT_DIR}/authentication/_index.md" "index generated by curate"
assert_file_contains "${CT_DIR}/authentication/_index.md" "JWT Best Practices" "index has title"

# --- Test: sync curate with manual source gives +10 importance ---
bash "$CT_SCRIPT" sync --action curate \
  --domain "api-design" \
  --topic "rest" \
  --title "REST Naming" \
  --tags "api" \
  --keywords "rest,naming" \
  --source "manual" \
  --from-agent "test" \
  --body "Use kebab-case."

MANUAL_FILE="${CT_DIR}/api-design/rest/rest-naming.md"
assert_file_exists "$MANUAL_FILE" "manual curate file created"
assert_file_contains "$MANUAL_FILE" "importance: 20" "manual curate importance boost"

# --- Test: sync query — searches and returns results ---
QUERY_RESULT=$(bash "$CT_SCRIPT" sync --action query --query "JWT token validation")
assert_contains "$QUERY_RESULT" "jwt-best-practices" "query found JWT file"

# --- Test: sync score — runs scoring pass on all files ---
bash "$CT_SCRIPT" sync --action score
assert_file_contains "$EXPECTED" "title:" "scoring preserved frontmatter"

# --- Test: sync archive — archives stale drafts ---
bash "$CT_SCRIPT" create \
  --domain "testing" --topic "old" \
  --title "Old Test Approach" --tags "test" --keywords "old" \
  --source "auto-curate" --from-agent "test" --body "Outdated approach."

OLD_FILE="${CT_DIR}/testing/old/old-test-approach.md"
sed -i '' 's/importance: 10/importance: 5/' "$OLD_FILE" 2>/dev/null || \
  sed -i 's/importance: 10/importance: 5/' "$OLD_FILE"

bash "$CT_SCRIPT" sync --action archive
assert_file_exists "${CT_DIR}/testing/old/old-test-approach.stub.md" "stale file archived by sync"

echo ""
echo "Sync tests: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ] || exit 1
