#!/usr/bin/env bash
# Start the model server for xgh (backend-aware: vllm-mlx or Ollama)
# Generated by xgh installer

set -euo pipefail

# Load model config from models.env if available
_MODELS_ENV="${HOME}/.xgh/models.env"
if [ -f "$_MODELS_ENV" ]; then
  # shellcheck disable=SC1090
  source "$_MODELS_ENV"
fi

XGH_BACKEND="${XGH_BACKEND:-vllm-mlx}"
XGH_LLM_MODEL="${XGH_LLM_MODEL:-mlx-community/Llama-3.2-3B-Instruct-4bit}"
XGH_EMBED_MODEL="${XGH_EMBED_MODEL:-mlx-community/nomicai-modernbert-embed-base-8bit}"
XGH_MODEL_PORT="${XGH_MODEL_PORT:-11434}"

if [ "$XGH_BACKEND" = "vllm-mlx" ]; then
  echo "Starting vllm-mlx model server..."
  echo "   LLM:        ${XGH_LLM_MODEL}"
  echo "   Embeddings: ${XGH_EMBED_MODEL}"
  echo "   Port:       ${XGH_MODEL_PORT}"
  echo ""
  exec vllm-mlx serve "${XGH_LLM_MODEL}" \
    --embedding-model "${XGH_EMBED_MODEL}" \
    --port "${XGH_MODEL_PORT}" \
    --host 127.0.0.1
else
  # Ollama backend
  echo "Ensuring Ollama models are pulled..."
  ollama pull "${XGH_LLM_MODEL}" 2>/dev/null || true
  ollama pull "${XGH_EMBED_MODEL}" 2>/dev/null || true
  exec ollama serve
fi
